app/controllers/boards_controller.rb, app/views/boards/show.html.erb, config/routes.rb, db/seeds.rb, test/controllers/boards_controller_test.rb
Show method done for board model
Descriptions added to seed to check layout and front
=> Board show

app/controllers/boards_controller.rb, app/views/boards/new.html.erb, config/routes.rb, test/controllers/boards_controller_test.rb
I wil make the new and the create actions and i will push the "new view".
=> Doing the new and create actions

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/controllers/boards_controller.rb, app/views/boards/index.html.erb, config/routes.rb, test/controllers/boards_controller_test.rb
=> Index board

app/controllers/boards_controller.rb, db/seeds.rb
end added line 13 of controller 
seed corrected
=> modifications done

app/assets/stylesheets/components/_card.scss, app/views/boards/index.html.erb
first image shown in index
clickable card which redirect to the show view
=> index with picture done

app/assets/stylesheets/components/_navbar.scss, app/views/boards/index.html.erb
=> such an improve

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_index.scss, app/views/boards/_form.html.erb
=> create design form

app/assets/stylesheets/components/_card.scss, app/views/boards/index.html.erb
=> design on cards

app/views/shared/_navbar.html.erb
=> link to logo

app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/pages/_show.scss, app/views/boards/show.html.erb
buton added in show to be able to book, link to be done
=> btn added in show

app/controllers/boards_controller.rb, app/controllers/bookings_controller.rb, app/views/boards/show.html.erb, config/routes.rb, test/controllers/bookings_controller_test.rb
booking controller and show view with form is created
=> create booking controler

app/controllers/admin/boards_controller.rb, app/controllers/admin/bookings_controller.rb, app/models/user.rb, app/views/admin/boards/index.html.erb, app/views/admin/bookings/index.html.erb, app/views/admin/bookings/show.html.erb, app/views/boards/_form.html.erb, app/views/boards/index.html.erb, app/views/boards/show.html.erb, app/views/shared/_index.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb, test/controllers/admin/boards_controller_test.rb, test/controllers/admin/bookings_controller_test.rb
Creation of admin routes and controllers for :
/admin/boards/index | GET
/admin/bookings/ | GET 
/admin/bookings/:id | GET
=> Admin creation

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_product-info.scss, app/assets/stylesheets/components/_user_info.scss, app/views/boards/show.html.erb
improve on design and adding profile info
=> Show design

app/controllers/bookings_controller.rb, app/javascript/controllers/datepicker_controller.js, app/javascript/controllers/toggle_controller.js, app/views/boards/_form.html.erb, app/views/boards/new.html.erb, app/views/boards/show.html.erb, app/views/layouts/application.html.erb, config/importmap.rb
2 controllers js / le form de crée
=> Form booking

app/views/admin/bookings/index.html.erb, app/views/boards/_form.html.erb, app/views/boards/new.html.erb, app/views/boards/show.html.erb, app/views/shared/_index.html.erb, app/views/shared/_navbar.html.erb
=> traduction

app/views/boards/show.html.erb
description issue solved, no error
=> description issue solved

app/views/admin/bookings/show.html.erb
solve issue with number float blocked 2 number after coma
=> float number

app/assets/stylesheets/components/_booking.scss, app/assets/stylesheets/components/_index.scss, app/views/boards/_form.html.erb, app/views/boards/show.html.erb, app/views/layouts/application.html.erb
=> Correct show

app/views/users/confirmations/new.html.erb, app/views/users/mailer/confirmation_instructions.html.erb, app/views/users/mailer/email_changed.html.erb, app/views/users/mailer/password_change.html.erb, app/views/users/mailer/reset_password_instructions.html.erb, app/views/users/mailer/unlock_instructions.html.erb, app/views/users/passwords/edit.html.erb, app/views/users/passwords/new.html.erb, app/views/users/sessions/new.html.erb, app/views/users/unlocks/new.html.erb, config/initializers/devise.rb
change in the config 
config.scoped_views = true
=> config.scoped_views = true

app/assets/stylesheets/components/_test.scss
=> change white text

app/assets/stylesheets/components/_test.scss, app/views/admin/bookings/index.html.erb
create the recap of bookings number
=> create the recap of bookings number

app/views/boards/index.html.erb
We have now the calculator display on the index view
=> create the calculator of number boards

app/assets/stylesheets/components/_booking.scss, app/assets/stylesheets/components/_card.scss, app/views/boards/new.html.erb, app/views/boards/show.html.erb, app/views/shared/_index.html.erb
=> Padding margin

app/views/admin/bookings/index.html.erb
Writing the dashboard for the users
=> change dashboard

app/views/admin/bookings/index.html.erb, app/views/admin/bookings/rents.html.erb
Create the new view for the locataires
=> page locataire

app/assets/stylesheets/components/_card.scss, app/views/boards/show.html.erb
=> adding card

app/views/boards/show.html.erb
=> center solved

app/controllers/bookings_controller.rb, app/javascript/controllers/reservation_modal_controller.js, app/views/boards/_form.html.erb, app/views/boards/show.html.erb
=> Modal bookings

app/views/boards/_form.html.erb
redirect to the show board page after click on the modal annuler
=> change redirect

app/assets/stylesheets/components/_mapbox.scss, app/assets/stylesheets/components/_user_info.scss, app/controllers/boards_controller.rb, app/views/boards/show.html.erb
=> map added on show

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_search_bar.scss, app/views/boards/_form.html.erb, app/views/boards/index.html.erb, app/views/layouts/application.html.erb
=> Search bar

app/assets/stylesheets/components/_btn-review.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_modal-body.scss, app/views/admin/bookings/index.html.erb, app/views/boards/_form.html.erb
update button to make it like all the other one and adding flex and space in modal
=> update button review + update on modal booking

app/controllers/admin/boards_controller.rb, app/views/admin/boards/edit.html.erb, app/views/admin/boards/index.html.erb, config/routes.rb
Made edit, update, destroy actions in the admin controllers
=> edit-update-destroy action

app/controllers/application_controller.rb, app/views/admin/boards/index.html.erb, app/views/users/registrations/new.html.erb, db/migrate/20230825103000_add_phone_number_to_users.rb, db/schema.rb
Add just phone number in the registration
=> add-phone-number

app/assets/stylesheets/components/_index.scss, app/views/admin/bookings/index.html.erb, app/views/admin/bookings/rents.html.erb, db/seeds.rb
seed more complete 
seed with phone_number
links in bookings to go on board show
=> seed completed and reviewed

db/seeds.rb
=> attached photo

db/seeds.rb
=> locations change

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_user_info.scss, app/views/boards/show.html.erb
=> change on avatar
